### ISSUE TITLE
Missing Bodyslide file

### ISSUE THREAD

**Issue by sgtsnicker** [ForgottenGlory/Masterstroke#43] opened 2022-02-28 08:50 UTC
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[Masterstroke Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**Masterstroke Version**
0.1.0

**Describe the bug**
Invisible armor (missing bodyslide)

**To Reproduce**
armor is equipped = invisible

**Expected behavior**
Armor appears as normal

**Screenshots**
![image](https://user-images.githubusercontent.com/100562762/155952447-e1c085ba-0a38-491f-a001-5daaa0c603b7.png)

If your report pertains to a specific NPC, object, or item, please open the console using the tilde (~) key and then click on that NPC, object or item. Take a screenshot of this and include that in this report. You will know if you have the correct thing selected if it is highlighted white after clicking on it.

**Additional context**
Item ID 0010D678

**Comment by ForgottenGlory** [comment] 2022-02-28 10:33
Duplicate of #26

**Closed as completed by ForgottenGlory** 2022-02-28 10:33 UTC
Labels: New Bug
