### ISSUE TITLE
Actions bound to X

### ISSUE THREAD

**Issue by Pudding9066** [ForgottenGlory/Masterstroke#65] opened 2022-03-06 18:08 UTC
**If you are reporting a crash to desktop, please attach your NET Script Framework crash log. This can be found in `[Masterstroke Install folder]\mods\Files Generated during playsessions launched with SKSE\NetScriptFramework\Crash`

If possible, please also attach a copy of your most recent save before the issue occurred.**

Please check back on your bug request periodically. I will ask for more details sometimes and if they are not provided I will eventually close the bug report.

**Masterstroke Version**
Beta

**Describe the bug**
There are (that I know of) three actions bound to the X key: QuckLight, Take Notes, and toggling the compass. The keymap indicates that opening Take Notes should be bound to B. 

**To Reproduce**
Press X. 

**Expected behavior**
One key bind per action.

**Screenshots**
n/a

**Additional context**
I remapped QuickLight to L and Take Notes to B.

**Comment by Pudding9066** [comment] 2022-03-06 18:27
Looks like it has already been addressed in #15.

**Comment by ForgottenGlory** [comment] 2022-03-19 13:20
Duplicate of #15

**Closed as completed by ForgottenGlory** 2022-03-19 13:20 UTC
Labels: Duplicate
