### ISSUE TITLE
Female College Mages invisible body

### ISSUE THREAD

**Issue by Listerw** [ForgottenGlory/Masterstroke#38] opened 2022-02-27 19:25 UTC
**Masterstroke Version**
Masterstroke Beta 1

**Describe the bug**
Female college mages have an invisible body

**To Reproduce**
Start at the frozen hearth inn. 
Head to the mages college. 
Faralda will have an invisible body. Heading to the college will show other female mages (like Mirabelle) with an invisible body.

**Expected behavior**
Body is visible

**Screenshots**
![image](https://user-images.githubusercontent.com/33641061/155896724-abc00233-c86c-4f18-9250-ca7ed9799e4a.png)

**Comment by Listerw** [comment] 2022-02-27 19:27
Save just outside the college [saves.zip](https://github.com/ForgottenGlory/Masterstroke/files/8149299/saves.zip)

**Comment by ForgottenGlory** [comment] 2022-02-27 21:14
Duplicate of #26

**Closed as completed by ForgottenGlory** 2022-02-27 21:14 UTC
Labels: New Bug
