### ISSUE TITLE
Free weapon generation from companion outfit manager.

### ISSUE THREAD

**Issue by catapsis** [ForgottenGlory/Masterstroke#50] opened 2022-03-01 01:13 UTC
**Masterstroke Version**
Beta 1

**Describe the bug**
The outfit manager will provide a free weapon to a companion that doesn't have one every time the outfit manager is used.

**To Reproduce**

1. Get a companion. 
2. Take away all their weapons.
3. Use the "Let me manage your outfit. -> Pick outfit," dialogue to open the companion outfit inventory.
5. Close out and let them equip the outfit.
6. Enter their inventory and observe that they have a weapon.
7. Take away that weapon.
8. Use the "Let me manage your outfit. -> Pick outfit," dialogue again.
9. Repeat from step 5 to collect an unlimited number of swords.

**Expected behavior**
The outfit manager shouldn't be handing out swords like the lady of the lake.

**Comment by ForgottenGlory** [comment] 2022-03-01 01:17
Duplicate of #49

**Closed as completed by ForgottenGlory** 2022-03-01 01:18 UTC
Labels: New Bug
