### ISSUE TITLE
Missing Bodyslide Texture - Vampire Armor

### ISSUE THREAD

**Issue by sgtsnicker** [ForgottenGlory/Masterstroke#44] opened 2022-02-28 10:25 UTC
**Masterstroke Version**
0.1.0

**Describe the bug**
Vampire Armor is insisible

**To Reproduce**
Equip Vampire Armor = invisible

**Expected behavior**
![SkyrimSE_xWn7Omd7yo](https://user-images.githubusercontent.com/100562762/155966177-5fe428a4-bc51-44a6-a8e5-7e643427196e.png)

The armor should not be invisible

**Screenshots**

**Additional context**
Item ID - 020191F3

**Comment by ForgottenGlory** [comment] 2022-02-28 10:33
Duplicate of #26

**Closed as completed by ForgottenGlory** 2022-02-28 10:33 UTC
Labels: New Bug
